Create Quarto site and setup GH Action
alan-turing-institute/teadt-community-survey pull request #95
Opened 2024-11-21 09:00 UTC by chrisdburr

This PR creates a quarto site, in the `site` directory and adds a GH action to automatically republish the site on merges into `main`.

No code is currently executed in the Quarto site. Any Jupyter notebooks referenced exist only on the GH repo.

2024-11-21 17:44 UTC, aranas commented
@chrisdburr This PR contains changes related to setting up the quarto page, correct?
Or are there any changes to the report text that I need to review?

2024-11-21 18:09 UTC, aranas commented on site/index.qmd
> +- News and Updates
I suggest we explicitly add a "News and Updates" Section to signal where people can expect to see news in the future. Could be directly below here or as new site. We can mention upcoming Gemini Call and publication of blogpost/report once ready

```suggestion
- News and Updates

## News & Updates

- We'll give a brief roundup of the survey results during a DT Hub [Gemini Call](https://digitaltwinhub.co.uk/gemini-call/) on Dec 3rd 2024 - Join us!
```

2024-11-22 10:14 UTC, chrisdburr commented
> @chrisdburr This PR contains changes related to setting up the quarto page, correct? Or are there any changes to the report text that I need to review?

No changes to your original `.md` files, but changes to the text as it is displayed in the Quarto site.

2024-11-28 13:10 UTC, aranas requested changes
I now had time to review your edits @chrisdburr , thank you very much for this work on the report. I think the context you have provided for some of the findings really helps understand the significance of the results! I have only corrected a small typo.

2024-11-28 13:10 UTC, aranas commented on site/analysis.qmd
> +In addition to the current practices and attitudes, a further key motivation for this survey was to better understand how the use and adoption of the Gemini Principles.
```suggestion
In addition to the current practices and attitudes, a further key motivation for this survey was to better understand the use and adoption of the Gemini Principles.
```

2024-11-28 13:34 UTC, merged